<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEEIEpVx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEEIEpVx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEEIEpVx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEEIEpVx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEEIEpVx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EEIEpVx',
    'container.build_id' => '4e5b5ad4',
    'container.build_time' => 1650723411,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEEIEpVx');
